# Generated by Django 5.1.5 on 2025-01-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="updated_at",
        ),
    ]
