# Generated by Django 5.1.5 on 2025-01-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0002_remove_subject_created_at_remove_subject_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
