# Generated by Django 5.1.5 on 2025-01-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="code",
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
