# Generated by Django 5.1.5 on 2025-01-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jome_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="MmMWuR3QO4cXF7kxXpnnX7XPxCffdgBy",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
