# Generated by Django 5.1.5 on 2025-01-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jome_auth", "0002_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="ZSpnVR6pBo1wZNHlAGG6rYtNC8oJJhq1",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
