# Generated by Django 5.1.5 on 2025-01-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jome_auth", "0008_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="8RKM8uDYiF3CXPpcbx0VUqrNSLKyk7Yw",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
