# Generated by Django 5.1.5 on 2025-01-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jome_auth", "0012_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="qExT7pHbn6P4N5SYOHSnA7PAV6dvQ33v",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
