# Generated by Django 5.1.5 on 2025-01-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jome_auth", "0014_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="Dv3Hinxh2gFucIBW67pUQhtj5xkMzdaf",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
