# Generated by Django 5.1.5 on 2025-01-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jome_auth", "0015_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="z3WK3DDRBcOWaBuHYW2TIKv54i9DHtdS",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
