# Generated by Django 5.1.5 on 2025-01-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jome_auth", "0016_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="AqmL4odasDWqq8P9hwaSybk5QrLUV6kf",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
