# Generated by Django 5.1.5 on 2025-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jome_auth", "0019_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="luwOwlTQey3SszU4wQb660Wl70RHtt2U",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
