# Generated by Django 5.1.5 on 2025-01-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jome_auth", "0020_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="dkcLbITlV0aSGmoqw3KUgqONQkyOSfZF",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
