# Generated by Django 5.1 on 2025-03-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jome_auth", "0021_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="cHcIDvJc5R8MvOOzPXR1qyrIe2u8afRI",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
