# Generated by Django 5.1.5 on 2025-01-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("subject", models.CharField(max_length=100)),
                ("years_of_experience", models.PositiveIntegerField()),
                ("date_joined", models.DateField(auto_now_add=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="teacher_pics/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
