# Generated by Django 5.1.5 on 2025-01-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0005_auto_20250129_1747"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="department",
        ),
    ]
