# Generated by Django 5.1.5 on 2025-01-29 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
        ("teachers", "0006_remove_teacher_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="departments.department",
            ),
            preserve_default=False,
        ),
    ]
