# Generated by Django 5.1.5 on 2025-01-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0007_teacher_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="department",
        ),
    ]
