# Generated by Django 5.1.5 on 2025-01-30 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0008_remove_teacher_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="num_of_teachers",
        ),
        migrations.AddField(
            model_name="teacher",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="teachers.department",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
