# Generated by Django 5.1.5 on 2025-01-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "teachers",
            "0009_remove_department_num_of_teachers_teacher_department_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="department",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
    ]
